# SMARTINTERNZ APPLIED DATA SCIENCE ASSIGNMENT-1

#NAME:D.JAYANTH VARMA
#REGISTRATION NUMBER:21BCE9786
# CAMPUS:VIT-AP
#SLOT-MORNING

**NUMPY EXERCISES**

**Import Numpy as np**

In [ ]:
import numpy as np

**create an array of 10 zeros**

In [ ]:
import numpy as np
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [ ]:
import numpy as np
f=np.ones(10)
f

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [ ]:
import numpy as np
k=np.repeat(5,10)
k

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

**Create an array of all the integers from 10 to 50**

In [ ]:
arr=np.arange(10,51,1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all even integers from 10 to 50**

In [ ]:
arr1=np.arange(10,51,2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3*3 matrix with values ranging from 0to 8**

In [ ]:
arr=np.arange(0,9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Create a Identity Matrix**

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use Numpy to generate a random number between o and 1**

In [ ]:
arr1=np.random.rand(1)
arr1

array([0.62489827])

**Use Numpy to generate a array of 25 numbers sampled froma standard normal distribution**

In [ ]:
rn=np.random.normal(0,1,25)
rn

array([-1.21971743,  0.08697829,  0.95039814,  1.34943374,  0.21480673,
       -1.59519463,  0.66704424, -0.38755992,  1.04198669, -0.42580891,
       -1.71012208,  0.10957434, -1.18846091, -0.96360297, -0.46501652,
        0.57556589, -0.68468908,  0.87419935,  1.67835624,  1.24887361,
        0.04086023,  0.92687279,  0.7925187 , -0.93716614,  0.23680181])

**create the following matrix**

In [ ]:
import numpy as np
ar1=np.arange(0.01,1.01,0.01)
a=ar1.reshape(10,10)
a

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Create an array of 20 linearly spaced points between 0 and 1**

In [ ]:
a=np.linspace(0,1,20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#NUMPY INDEXING AND SELECTION

In [ ]:
arr1=np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
 #BE ABLE TO SEE THE OUTPUT ANY MORE

k=np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
k

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
 #BE ABLE TO SEE THE OUTPUT ANY MORE
k[1][3]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
 #BE ABLE TO SEE THE OUTPUT ANY MORE
arr1[0:3,1]

array([ 2,  7, 12])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
 #BE ABLE TO SEE THE OUTPUT ANY MOREarr1[-1]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
 #BE ABLE TO SEE THE OUTPUT ANY MOREarr1[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Now do the following

**Get the sum of all values in arr1**

In [ ]:
np.sum(arr1)

325

**Get the Standard Deviation of the values in arr1**

In [ ]:
np.std(arr1)

7.211102550927978

**Get the sum of all the columns in arr1**

In [ ]:
arr1.sum(axis=0)

array([55, 60, 65, 70, 75])